version: '2'

services:
  auth:
    image: MY_ACCOUNT_ID.dkr.ecr.MY_REGION.amazonaws.com/waku-waku-auth:latest
    env_file:
      - ./auth/.env
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "MY_REGION"
        awslogs-group: "waku-waku-log-group"
        awslogs-stream: "auth-stream"
  client:
    image: MY_ACCOUNT_ID.dkr.ecr.MY_REGION.amazonaws.com/waku-waku-client:latest
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "MY_REGION"
        awslogs-group: "waku-waku-log-group"
        awslogs-stream: "nginx-stream"
    volumes:
      - type: bind
        source: /var/www/certbot
        target: /var/www/certbot
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
  db:
    image: MY_ACCOUNT_ID.dkr.ecr.MY_REGION.amazonaws.com/waku-waku-db:latest
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "MY_REGION"
        awslogs-group: "waku-waku-log-group"
        awslogs-stream: "db-stream"
  sfu:
    image: MY_ACCOUNT_ID.dkr.ecr.MY_REGION.amazonaws.com/waku-waku-sfu:latest
    env_file:
      - ./sfu/.env
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "MY_REGION"
        awslogs-group: "waku-waku-log-group"
        awslogs-stream: "sfu-stream"
